apiVersion: v1
kind: Secret
metadata:
  name: dojo-backup-google
type: Opaque
stringData:
  service-account.json: replace-with-google-service-account-json
  rclone.conf: |
    [gdrive]
    type = drive
    scope = drive.file
    service_account_file = /google-backup/service-account.json
