apiVersion: v1
kind: Secret
metadata:
  name: dojo-backup-google
type: Opaque
stringData:
  client-id: replace-with-google-oauth-client-id
  client-secret: replace-with-google-oauth-client-secret
  refresh-token: replace-with-google-oauth-refresh-token
