apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dojo-prod

resources:
- ../../base

patches:
- path: deployment-patch.yaml
- target:
    kind: PersistentVolumeClaim
    name: dojo-data
  patch: |-
    - op: replace
      path: /metadata/name
      value: dojo-prod-data-zfs
    - op: replace
      path: /spec/resources/requests/storage
      value: 5Gi

images:
- name: ghcr.io/blogle/dojo2
  newName: ghcr.io/blogle/dojo2
  digest: sha256:REPLACE_WITH_BUILD_DIGEST
