from __future__ import annotations

from uuid import UUID

MAX_TS = "9999-12-31 23:59:59+00"

SYSTEM_CATEGORY_ATB = "TX_AVAILABLE_TO_BUDGET"
SYSTEM_CATEGORY_STARTING_BALANCE = "TX_STARTING_BALANCE"
SYSTEM_CATEGORY_TRANSFER = "TX_ACCOUNT_TRANSFER"
SYSTEM_CATEGORY_BALANCE_ADJUSTMENT = "TX_BALANCE_ADJUSTMENT"

BUCKET_TYPE_ATB = "BUCKET_AVAILABLE_TO_BUDGET"
BUCKET_TYPE_CATEGORY = "BUCKET_CATEGORY"

CATEGORY_KIND_STANDARD = "STANDARD"
CATEGORY_KIND_CREDIT_CARD_PAYMENT = "CREDIT_CARD_PAYMENT"

ACCOUNT_CLASS_BUDGET = "BUDGET"
ACCOUNT_CLASS_TRACKING = "TRACKING"
ACCOUNT_CLASS_INVESTMENT = "INVESTMENT"
ACCOUNT_CLASS_LOAN = "LOAN"
ACCOUNT_CLASS_TANGIBLE_ASSET = "TANGIBLE_ASSET"

BUDGET_ACCOUNT_TYPE_DEPOSIT = "DEPOSIT"
BUDGET_ACCOUNT_TYPE_CREDIT_CARD = "CREDIT_CARD"

LINK_BEHAVIOR_CREDIT_CARD_PAYMENT = "CREDIT_CARD_PAYMENT"
LINK_BEHAVIOR_INVESTMENT_CONTRIBUTION = "INVESTMENT_CONTRIBUTION"
LINK_BEHAVIOR_LOAN_PAYMENT = "LOAN_PAYMENT"

DERIVATION_METHOD_CC_SPEND_AND_TRANSFER = "CC_SPEND_AND_TRANSFER"
DERIVATION_METHOD_TRANSFER_IN_ONLY = "TRANSFER_IN_ONLY"
DERIVATION_METHOD_NONE = "NONE"

# Default derivation methods for each link behavior
DEFAULT_DERIVATION_METHOD_BY_BEHAVIOR = {
    LINK_BEHAVIOR_CREDIT_CARD_PAYMENT: DERIVATION_METHOD_CC_SPEND_AND_TRANSFER,
    LINK_BEHAVIOR_INVESTMENT_CONTRIBUTION: DERIVATION_METHOD_TRANSFER_IN_ONLY,
    LINK_BEHAVIOR_LOAN_PAYMENT: DERIVATION_METHOD_TRANSFER_IN_ONLY,
}

STATUS_PENDING = "PENDING"
STATUS_CLEARED = "CLEARED"

SYSTEM_CREDIT_CARD_GROUP_ID = UUID("00000000-0000-0000-0000-00000000cc01")
SYSTEM_ATB_BUCKET_ID = UUID("00000000-0000-0000-0000-00000000a7b0")

GOOGLE_SHEETS_READONLY_SCOPE = "https://www.googleapis.com/auth/spreadsheets.readonly"

SUPPORTED_IMPORT_TABS = (
    "Configuration",
    "Transactions",
    "Category Allocation",
    "Net Worth Reports",
)

REQUIRED_TRANSACTION_HEADERS = (
    "DATE",
    "OUTFLOW",
    "INFLOW",
    "CATEGORY",
    "ACCOUNT",
    "MEMO",
    "STATUS",
)

REQUIRED_ALLOCATION_HEADERS = (
    "DATE",
    "AMOUNT",
    "FROM CATEGORY",
    "TO CATEGORY",
    "MEMO",
)

REQUIRED_NET_WORTH_HEADERS = (
    "DATE",
    "AMOUNT",
    "NET WORTH CATEGORY",
    "NOTES",
)
