from __future__ import annotations

from uuid import UUID

MAX_TS = "9999-12-31 23:59:59+00"

SYSTEM_CATEGORY_ATB = "TX_AVAILABLE_TO_BUDGET"
SYSTEM_CATEGORY_STARTING_BALANCE = "TX_STARTING_BALANCE"
SYSTEM_CATEGORY_TRANSFER = "TX_ACCOUNT_TRANSFER"
SYSTEM_CATEGORY_BALANCE_ADJUSTMENT = "TX_BALANCE_ADJUSTMENT"

BUCKET_TYPE_ATB = "BUCKET_AVAILABLE_TO_BUDGET"
BUCKET_TYPE_CATEGORY = "BUCKET_CATEGORY"

CATEGORY_KIND_STANDARD = "STANDARD"
CATEGORY_KIND_CREDIT_CARD_PAYMENT = "CREDIT_CARD_PAYMENT"

ACCOUNT_CLASS_BUDGET = "BUDGET"
ACCOUNT_CLASS_TRACKING_BALANCE = "TRACKING_BALANCE"
ACCOUNT_CLASS_TRACKING_POSITIONS = "TRACKING_POSITIONS"
ACCOUNT_CLASS_TRACKING_DEBT = "TRACKING_DEBT"

BUDGET_ACCOUNT_TYPE_DEPOSIT = "DEPOSIT"
BUDGET_ACCOUNT_TYPE_CREDIT_CARD = "CREDIT_CARD"

STATUS_PENDING = "PENDING"
STATUS_CLEARED = "CLEARED"

SYSTEM_CREDIT_CARD_GROUP_ID = UUID("00000000-0000-0000-0000-00000000cc01")
SYSTEM_ATB_BUCKET_ID = UUID("00000000-0000-0000-0000-00000000a7b0")

GOOGLE_SHEETS_READONLY_SCOPE = "https://www.googleapis.com/auth/spreadsheets.readonly"

SUPPORTED_IMPORT_TABS = (
    "Configuration",
    "Transactions",
    "Category Allocation",
    "Net Worth Reports",
)

REQUIRED_TRANSACTION_HEADERS = (
    "DATE",
    "OUTFLOW",
    "INFLOW",
    "CATEGORY",
    "ACCOUNT",
    "MEMO",
    "STATUS",
)

REQUIRED_ALLOCATION_HEADERS = (
    "DATE",
    "AMOUNT",
    "FROM CATEGORY",
    "TO CATEGORY",
    "MEMO",
)

REQUIRED_NET_WORTH_HEADERS = (
    "DATE",
    "AMOUNT",
    "NET WORTH CATEGORY",
    "NOTES",
)
