import type { Account, Category, CategoryGroup, Transaction } from "../src/dojo/types";

export const sampleAccounts: Account[] = [
  {
    account_id: "account-1",
    name: "Checking",
    account_class: "BUDGET",
    is_hidden: false,
    is_active: true,
    budget_account_type: "DEPOSIT",
    actual_balance_minor: 100000,
    pending_balance_minor: 0,
    cleared_balance_minor: 100000,
    display_balance_minor: 100000,
  },
  {
    account_id: "account-2",
    name: "Reserve Card",
    account_class: "BUDGET",
    is_hidden: false,
    is_active: true,
    budget_account_type: "CREDIT_CARD",
    actual_balance_minor: -20000,
    pending_balance_minor: 0,
    cleared_balance_minor: -20000,
    display_balance_minor: 20000,
  },
];

export const sampleCategories: Category[] = [
  {
    category_id: "cat-1",
    bucket_id: "bucket-1",
    group_id: "group-1",
    group_name: "Living",
    name: "Grocery",
    category_kind: "STANDARD",
    sort_order: 10,
    is_hidden: false,
    is_active: true,
    target_amount_minor: 0,
    due_date_rule: null,
    available_minor: 20000,
    month_activity_minor: -5000,
    month_budgeted_minor: 10000,
    starting_available_minor: 15000,
  },
  {
    category_id: "cat-2",
    bucket_id: "bucket-2",
    group_id: "group-1",
    group_name: "Living",
    name: "Hidden stash",
    category_kind: "STANDARD",
    sort_order: 20,
    is_hidden: true,
    is_active: true,
    target_amount_minor: 0,
    due_date_rule: null,
    available_minor: 5000,
    month_activity_minor: 0,
    month_budgeted_minor: 5000,
    starting_available_minor: 0,
  },
  {
    category_id: "cat-3",
    bucket_id: "bucket-3",
    group_id: "group-2",
    group_name: "Credit Card Payments",
    name: "Reserve Card Payment",
    category_kind: "CREDIT_CARD_PAYMENT",
    sort_order: 10,
    is_hidden: false,
    is_active: true,
    target_amount_minor: null,
    due_date_rule: null,
    available_minor: 15000,
    month_activity_minor: 0,
    month_budgeted_minor: 15000,
    starting_available_minor: 0,
  },
];

export const sampleGroup: CategoryGroup = {
  group_id: "group-1",
  name: "Living",
  sort_order: 10,
  is_hidden: false,
  is_system: false,
  is_deletable: true,
  totals: {
    available_minor: 25000,
    month_activity_minor: -5000,
    month_budgeted_minor: 15000,
    starting_available_minor: 15000,
  },
  categories: [sampleCategories[0], sampleCategories[1]],
};

export const sampleTransactions: Transaction[] = Array.from({ length: 120 }, (_, index) => ({
  transaction_id: `tx-${index}`,
  date: "2026-02-03",
  account_id: "account-1",
  account_name: "Checking",
  amount_minor: -100 - index,
  category_id: "cat-1",
  category_name: "Grocery",
  system_category: null,
  status: index % 2 === 0 ? "CLEARED" : "PENDING",
  memo: `memo-${index}`,
  is_hidden_entity: false,
}));
